update scripts

diff --git a/bin/0xff b/bin/0xff
--- a/bin/0xff
+++ b/bin/0xff
@@ -6,36 +6,52 @@
 
 usage() {
   cat <<EOF
-Usage: $(basename "$0") [-h] URL
+Usage: $(basename "${0}") [option] <url>
 
-  URL  URL to be shortened
-  -h   display this help message and exit
+  -h, --help  display this help message and exit
 EOF
 }
 
-while getopts ":h" opt; do
-  case $opt in
-    h)
+0xff() {
+  CURL=$(which curl)
+  SHORTENER_URL="https://0xff.tf"
+  SHORTENER_SECRET_KEY="${ENV_SHORTENER_SECRET_KEY}"
+
+  RESPONSE=$("${CURL}" --silent --fail -X POST \
+            -H "Authorization: ${SHORTENER_SECRET_KEY}" \
+            -H "URL: $1" ${SHORTENER_URL}) || {
+      echo "ERROR: failed to shorten" >&2
+      exit 1
+  }
+
+  echo "${RESPONSE}" | grep -o '"short":"[^"]*' | grep -o '[^"]*$'
+
+  unset CURL
+  unset RESPONSE
+  unset SHORTENER_URL
+  unset SHORTENER_SECRET_KEY
+}
+
+if [ "$#" -eq 0 ]; then
+  echo "$(basename "${0}"): missing argument"
+  echo "Try '$(basename "${0}") -h' for more information."
+  exit 1
+fi
+
+while true; do
+  case "${1}" in
+    "-h"|"--help")
       usage
       exit 0
       ;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
+    -?*)
+      echo "$(basename "${0}"): Invalid option $1"
+      echo "Try '$(basename "${0}") -h' for more information."
       exit 1
+      ;;
+    *)
+      0xff "${1}"
+      break
       ;;
   esac
 done
-
-[ $# -eq 0 ] && { echo "Error: URL is required"; exit 1; }
-
-SHORTENER_URL="https://0xff.tf"
-SHORTENER_SECRET_KEY=${ENV_SHORTENER_SECRET_KEY}
-
-RESPONSE=$(curl --silent --fail -X POST \
-          -H "Authorization: $SHORTENER_SECRET_KEY" \
-          -H "URL: $1" $SHORTENER_URL) || {
-    echo "ERROR: failed to shorten" >&2
-    exit 1
-}
-
-echo "$RESPONSE" | grep -o '"short":"[^"]*' | grep -o '[^"]*$'
diff --git a/bin/httpc b/bin/httpc
--- a/bin/httpc
+++ b/bin/httpc
@@ -5,28 +5,14 @@
 
 usage() {
   cat <<EOF
-Usage: $(basename "$0") [-h] CODE
+Usage: $(basename "${0}") [option] <code>
 
-  CODE  get information about HTTP code
-  -h    display this help message and exit
+  -h, --help  display this help message and exit
 EOF
 }
 
-while getopts ":h" opt; do
-  case $opt in
-    h)
-      usage
-      exit 0
-      ;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
-      exit 1
-      ;;
-  esac
-done
-
-get_http_status_text() {
-  case $1 in
+status_text() {
+  case "${1}" in
     100) echo "Continue";;
     101) echo "Switching Protocols";;
     102) echo "Processing (WebDAV; RFC 2518)";;
@@ -143,19 +129,49 @@ get_http_status_text() {
   esac
 }
 
-get_wikipedia_link() {
-  echo "https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#$1"
+wiki_link() {
+  echo "https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#${1}"
 }
 
-[ $# -eq 0 ] && { echo "Usage: $(basename "$0") <CODE>"; exit 1; }
+code() {
+  HTTP_TEXT=$(status_text "${1}")
 
-HTTP_TEXT=$(get_http_status_text "$1")
+  if [ "${HTTP_TEXT}" = "Unknown HTTP Code" ]; then
+    echo "${1} - ${HTTP_TEXT}"
+    exit 1
+  fi
 
-if [ "$HTTP_TEXT" = "Unknown HTTP Code" ]; then
-  echo "$HTTP_TEXT"
+  WIKIPEDIA_LINK=$(wiki_link "${1}")
+
+  echo "${1} ${HTTP_TEXT} - ${WIKIPEDIA_LINK}"
+
+  unset HTTP_TEXT
+  unset WIKIPEDIA_LINK
+}
+
+if [ "$#" -eq 0 ]; then
+  echo "$(basename "${0}"): missing argument"
+  echo "Try '$(basename "${0}") -h' for more information."
   exit 1
 fi
 
-WIKIPEDIA_LINK=$(get_wikipedia_link "$1")
+while true; do
+  case "${1-}" in
+    "-h"|"--help")
+      usage
+      exit 0
+      ;;
+    -?*)
+      echo "$(basename "${0}"): Invalid option $1"
+      echo "Try '$(basename "${0}") -h' for more information."
+      exit 1
+      ;;
+    *)
+      code "$@"
+      break
+      ;;
+  esac
+  shift
+done
 
-echo "$1 $HTTP_TEXT - $WIKIPEDIA_LINK"
+
diff --git a/bin/vault b/bin/vault
--- a/bin/vault
+++ b/bin/vault
@@ -6,37 +6,54 @@
 
 usage() {
   cat <<EOF
-Usage: $(basename "$0") [-h] FILE
+Usage: $(basename "${0}") [option] <file>
 
-  FILE  path to file
-  -h    display this help message and exit
+  -h, --help  display this help message and exit
 EOF
 }
 
-while getopts ":h" opt; do
-  case $opt in
-    h)
+vault() {
+  CURL=$(which curl)
+  VAULT_URL="https://vault.tf"
+  VAULT_SECRET_KEY="${ENV_VAULT_SECRET_KEY}"
+
+  RESPONSE=$("${CURL}" --silent --fail --data-binary @"${1:--}" \
+       -H "Authorization: $VAULT_SECRET_KEY" "$VAULT_URL/documents") || {
+      echo "ERROR: failed to paste" >&2
+      exit 1
+  }
+
+  VAULT_KEY=$(echo "$RESPONSE" | grep -o '"key":"[^"]*' | grep -o '[^"]*$')
+
+  echo "${VAULT_URL}"/"${VAULT_KEY}"
+
+  unset CURL
+  unset VAULT_URL
+  unset VAULT_KEY
+  unset VAULT_SECRET_KEY
+}
+
+if [ "$#" -eq 0 ]; then
+  echo "$(basename "${0}"): missing argument"
+  echo "Try '$(basename "${0}") -h' for more information."
+  exit 1
+fi
+
+while true; do
+  case "${1-}" in
+    "-h"|"--help")
       usage
       exit 0
       ;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
+    -?*)
+      echo "$(basename "${0}"): Invalid option ${1}"
+      echo "Try '$(basename "${0}") -h' for more information."
       exit 1
       ;;
+    *)
+      vault "$@"
+      break
+      ;;
   esac
+  shift
 done
-
-[ $# -eq 0 ] && { echo "Error: FILE is required"; exit 1; }
-
-VAULT_URL="https://vault.tf"
-VAULT_SECRET_KEY=${ENV_VAULT_SECRET_KEY}
-
-RESPONSE=$(curl --silent --fail --data-binary @"${1:--}" \
-     -H "Authorization: $VAULT_SECRET_KEY" "$VAULT_URL/documents") || {
-    echo "ERROR: failed to paste" >&2
-    exit 1
-}
-
-VAULT_KEY=$(echo "$RESPONSE" | grep -o '"key":"[^"]*' | grep -o '[^"]*$')
-
-echo "$VAULT_URL"/"$VAULT_KEY"
diff --git a/bin/weather b/bin/weather
--- a/bin/weather
+++ b/bin/weather
@@ -6,31 +6,47 @@
 
 usage() {
   cat <<EOF
-Usage: $(basename "$0") [-h] [-l LOCATION]
+Usage: $(basename "${0}") [option]
 
-  -l LOCATION  any location types (default: Luxembourg,Luxembourg)
-  -h           display this help message and exit
+  -l, --location  return weather for location (default: Luxembourg,Luxembourg)
+
+  -h, --help      display this help message and exit
 EOF
 }
 
-while getopts ":hl:" opt; do
-  case $opt in
-    h)
+query() {
+  CURL=$(which curl)
+
+  if ! RESPONSE=$("${CURL}" --disable --fail --silent --compressed https://wttr.in/${LOCATION:-Luxembourg,Luxembourg}?2nqmF); then
+    echo "$(basename "${0}"): check your internet connection and try again"
+    exit 1
+  fi
+
+  echo "${RESPONSE}"
+
+  unset CURL
+  unset RESPONSE
+}
+
+while true; do
+  case "${1-}" in
+    "-h"|"--help")
       usage
       exit 0
       ;;
-    l)
-      LOCATION="$OPTARG"
+    "-l"|"--location")
+      LOCATION="${2-}"
+      shift
       ;;
-    \?)
-      echo "Invalid option: -$OPTARG" >&2
+    -?*)
+      echo "$(basename "${0}"): Invalid option ${1}"
+      echo "Try '$(basename "${0}") -h' for more information."
       exit 1
       ;;
-    :)
-      echo "Option -$OPTARG requires an argument." >&2
-      exit 1
+    *)
+      query "$@"
+      exit 0
       ;;
   esac
+  shift
 done
-
-curl -fGsS --compressed "wttr.in/${LOCATION:-Luxembourg,Luxembourg}?2nqmF"
diff --git a/bin/whatsmyip b/bin/whatsmyip
--- a/bin/whatsmyip
+++ b/bin/whatsmyip
@@ -1,6 +1,68 @@
 #!/bin/sh
 #
-# whatsmyip - return public IP address
+# whatsmyip - return public IPv[4|6] address
 #
 
-curl -fGsS --compressed https://icanhazip.com/
+# TODO:
+# - add -s/--strip option to allow for removal of newline `\n` from output
+
+usage() {
+  cat <<EOF
+Usage: $(basename "${0}") [option]
+
+  -4, --IPv4   return public IPv4 if present
+  -6, --IPv6   return public IPv6 if present
+  -a, --all    return both IPv4 and IPv6 if present
+
+  -h, --help   display this help message and exit
+EOF
+}
+
+query() {
+  CURL=$(which curl)
+
+  if ! RESPONSE=$("${CURL}" --disable --fail --silent --compressed https://"${PROTO:-ipv4}".icanhazip.com/); then
+    echo "$(basename "${0}"): check your internet connection and try again"
+    exit 1
+  fi
+
+  echo "${RESPONSE}"
+
+  unset CURL
+  unset RESPONSE
+}
+
+while true; do
+  case "${1-}" in
+    "-h"|"--help")
+      usage
+      exit 0
+      ;;
+    "-4"|"--IPv4")
+      PROTO="ipv4"
+      query
+      exit 0
+      ;;
+    "-6"|"--IPv6")
+      PROTO="ipv6"
+      query
+      exit 0
+      ;;
+    "-a"|"--all")
+      PROTO="ipv4"
+      query
+      PROTO="ipv6"
+      query
+      exit 0
+      ;;
+    -?*)
+      echo "$(basename "${0}"): Invalid option ${1}"
+      echo "Try '$(basename "${0}") -h' for more information."
+      exit 1
+      ;;
+    *)
+      query
+      exit 0
+      ;;
+  esac
+done
