loads of small improvements

diff --git a/bin/0xff b/bin/0xff
--- a/bin/0xff
+++ b/bin/0xff
@@ -1,16 +1,38 @@
 #!/bin/sh
 #
-# 0xff - shorten URLs
+# 0xff - 0xff.tf CLI client
 # https://github.com/barnumbirr/0xff
 #
 
-[ $# -eq 0 ] && { echo "Usage: $0 <FILE_PATH>"; exit 1; }
+usage() {
+  cat <<EOF
+Usage: $(basename "$0") [-h] URL
+
+  URL  URL to be shortened
+  -h   display this help message and exit
+EOF
+}
+
+while getopts ":h" opt; do
+  case $opt in
+    h)
+      usage
+      exit 0
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
+
+[ $# -eq 0 ] && { echo "Error: URL is required"; exit 1; }
 
 SHORTENER_URL="https://0xff.tf"
 SHORTENER_SECRET_KEY=${ENV_SHORTENER_SECRET_KEY}
 
 RESPONSE=$(curl --silent --fail -X POST \
-          -H "Authorization: $SHORTENER_SECRET_KEY"\
+          -H "Authorization: $SHORTENER_SECRET_KEY" \
           -H "URL: $1" $SHORTENER_URL) || {
     echo "ERROR: failed to shorten" >&2
     exit 1
diff --git a/bin/http b/bin/http
--- a/bin/http
+++ b/bin/http
@@ -3,7 +3,27 @@
 # http - HTTP status code information
 #
 
-[ $# -eq 0 ] && { echo "Usage: $0 <HTTP_CODE>"; exit 1; }
+usage() {
+  cat <<EOF
+Usage: $(basename "$0") [-h] CODE
+
+  CODE  get information about HTTP code
+  -h    display this help message and exit
+EOF
+}
+
+while getopts ":h" opt; do
+  case $opt in
+    h)
+      usage
+      exit 0
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
 
 get_http_status_text() {
   case $1 in
@@ -127,7 +147,7 @@ get_wikipedia_link() {
   echo "https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#$1"
 }
 
-[ $# -eq 0 ] && { echo "Usage: $0 <FILE_PATH>"; exit 1; }
+[ $# -eq 0 ] && { echo "Usage: $(basename "$0") <CODE>"; exit 1; }
 
 HTTP_TEXT=$(get_http_status_text "$1")
 
diff --git a/bin/vault b/bin/vault
--- a/bin/vault
+++ b/bin/vault
@@ -4,7 +4,29 @@
 # https://github.com/barnumbirr/vault
 #
 
-[ $# -eq 0 ] && { echo "Usage: $0 <FILE_PATH>"; exit 1; }
+usage() {
+  cat <<EOF
+Usage: $(basename "$0") [-h] FILE
+
+  FILE  path to file
+  -h    display this help message and exit
+EOF
+}
+
+while getopts ":h" opt; do
+  case $opt in
+    h)
+      usage
+      exit 0
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+  esac
+done
+
+[ $# -eq 0 ] && { echo "Error: FILE is required"; exit 1; }
 
 VAULT_URL="https://vault.tf"
 VAULT_SECRET_KEY=${ENV_VAULT_SECRET_KEY}
diff --git a/bin/weather b/bin/weather
--- a/bin/weather
+++ b/bin/weather
@@ -1,9 +1,36 @@
 #!/bin/sh
 #
-# weather - Weather forecast
+# weather - weather forecast
 # https://github.com/chubin/wttr.in
 #
 
-LOC="${1:-Luxembourg,Luxembourg}"
+usage() {
+  cat <<EOF
+Usage: $(basename "$0") [-h] [-l LOCATION]
 
-curl -fGsS --compressed "v2.wttr.in/${LOC}"
+  -l LOCATION  any location types (default: Luxembourg,Luxembourg)
+  -h           display this help message and exit
+EOF
+}
+
+while getopts ":hl:" opt; do
+  case $opt in
+    h)
+      usage
+      exit 0
+      ;;
+    l)
+      LOCATION="$OPTARG"
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
+curl -fGsS --compressed "wttr.in/${LOCATION:-Luxembourg,Luxembourg}?2nqmF"
