update most scripts in /root/bin

diff --git a/bin/0xff b/bin/0xff
--- a/bin/0xff
+++ b/bin/0xff
@@ -6,14 +6,15 @@
 
 usage() {
   cat <<EOF
-Usage: $(basename "${0}") [option] <url>
+Usage: $(basename "${0}") [options] URL
 
-  -h, --help  display this help message and exit
+  -V, --verbose    output debug information
+  -h, --help       display this help message and exit
 EOF
 }
 
 _0xff() {
-  CURL=$(which curl)
+  CURL=$(command -v curl)
   SHORTENER_URL="https://0xff.tf"
   SHORTENER_SECRET_KEY="${SHORTENER_SECRET_KEY}"
 
@@ -32,26 +33,35 @@ _0xff() {
   unset SHORTENER_SECRET_KEY
 }
 
-if [ "$#" -eq 0 ]; then
-  echo "$(basename "${0}"): missing argument"
-  echo "Try '$(basename "${0}") -h' for more information."
-  exit 1
-fi
+parse_params() {
+  while true; do
+    case "${1-}" in
+      "-h"|"--help")
+        usage
+        exit 0
+        ;;
+      "-V"|"--verbose")
+        set -x
+        ;;
+      -?*)
+        echo "$(basename "${0}"): Invalid option ${1}"
+        echo "Try '$(basename "${0}") -h' for more information."
+        exit 1
+        ;;
+      *)
+        break
+        ;;
+    esac
+    shift
+  done
 
-while true; do
-  case "${1}" in
-    "-h"|"--help")
-      usage
-      exit 0
-      ;;
-    -?*)
-      echo "$(basename "${0}"): Invalid option $1"
-      echo "Try '$(basename "${0}") -h' for more information."
-      exit 1
-      ;;
-    *)
-      _0xff "${1}"
-      break
-      ;;
-  esac
-done
+  if [ -z "$1" ]; then
+    echo "$(basename "${0}"): URL is required."
+    echo "Try '$(basename "${0}") -h' for more information."
+    exit 1
+  fi
+
+  _0xff "$@"
+}
+
+parse_params "$@"
diff --git a/bin/cert b/bin/cert
--- a/bin/cert
+++ b/bin/cert
@@ -5,14 +5,15 @@
 
 usage() {
   cat <<EOF
-Usage: $(basename "${0}") [option] <domain>
+Usage: $(basename "${0}") [options] DOMAIN
 
-  -h, --help  display this help message and exit
+  -V, --verbose    output debug information
+  -h, --help       display this help message and exit
 EOF
 }
 
 main() {
-  OPENSSL=$(which openssl)
+  OPENSSL=$(command -v openssl)
   RESULT=$(echo | "${OPENSSL}" s_client -showcerts -servername "${1}" -connect "${1}:443" 2>/dev/null)
 
   if [ $? -eq 0 ]; then
@@ -26,26 +27,35 @@ main() {
   unset RESULT
 }
 
-if [ "$#" -eq 0 ]; then
-  echo "$(basename "${0}"): missing argument"
-  echo "Try '$(basename "${0}") -h' for more information."
-  exit 1
-fi
+parse_params() {
+  while true; do
+    case "${1-}" in
+      "-h"|"--help")
+        usage
+        exit 0
+        ;;
+      "-V"|"--verbose")
+        set -x
+        ;;
+      -?*)
+        echo "$(basename "${0}"): Invalid option ${1}"
+        echo "Try '$(basename "${0}") -h' for more information."
+        exit 1
+        ;;
+      *)
+        break
+        ;;
+    esac
+    shift
+  done
 
-while true; do
-  case "${1-}" in
-    "-h"|"--help")
-      usage
-      exit 0
-      ;;
-    -?*)
-      echo "$(basename "${0}"): Invalid option ${1}"
-      echo "Try '$(basename "${0}") -h' for more information."
-      exit 1
-      ;;
-    *)
-      main "${1}"
-      break
-      ;;
-  esac
-done
+  if [ -z "$1" ]; then
+    echo "$(basename "${0}"): DOMAIN is required."
+    echo "Try '$(basename "${0}") -h' for more information."
+    exit 1
+  fi
+
+  main "$@"
+}
+
+parse_params "$@"
diff --git a/bin/duh b/bin/duh
--- a/bin/duh
+++ b/bin/duh
@@ -5,12 +5,13 @@
 
 usage() {
   cat <<EOF
-Usage: $(basename "$0") [option]
+Usage: $(basename "$0") [parameters] [options]
 
-  -d  set working directory (default: \$PWD)
-  -n  return number of lines (default: 20)
+  -d, --directory DIRECTORY    set working directory (default: \$PWD)
+  -n, --number NUMBER          return number of lines (default: 20)
 
-  -h  display this help message and exit
+  -V, --verbose                output debug information
+  -h, --help                   display this help message and exit
 EOF
 }
 
@@ -21,29 +22,37 @@ main() {
   head -n "${NUMBER:-20}"
 }
 
-while true; do
-  case "${1-}" in
-    "-h"|"--help")
-      usage
-      exit 0
-      ;;
-    "-d"|"--directory")
-      DIRECTORY="${2-}"
-      shift
-      ;;
-    "-n"|"--number")
-      NUMBER="${2-}"
-      shift
-      ;;
-    -?*)
-      echo "$(basename "${0}"): Invalid option $1"
-      echo "Try '$(basename "${0}") -h' for more information."
-      exit 1
-      ;;
-    *)
-      main "$@"
-      break
-      ;;
-  esac
-  shift
-done
+parse_params() {
+  while true; do
+    case "${1-}" in
+      "-h"|"--help")
+        usage
+        exit 0
+        ;;
+      "-d"|"--directory")
+        DIRECTORY="${2-}"
+        shift
+        ;;
+      "-n"|"--number")
+        NUMBER="${2-}"
+        shift
+        ;;
+      "-V"|"--verbose")
+        set -x
+        ;;
+      -?*)
+        echo "$(basename "${0}"): Invalid option ${1}"
+        echo "Try '$(basename "${0}") -h' for more information."
+        exit 1
+        ;;
+      *)
+        break
+        ;;
+    esac
+    shift
+  done
+
+  main "$@"
+}
+
+parse_params "$@"
diff --git a/bin/gh-release b/bin/gh-release
--- a/bin/gh-release
+++ b/bin/gh-release
@@ -6,14 +6,16 @@
 
 usage() {
   cat <<EOF
-Usage: $(basename "${0}") [option] <username/repo>
+Usage: $(basename "${0}") [options] USERNAME/REPO
 
-  -h, --help  display this help message and exit
+  -V, --verbose    output debug information
+  -h, --help       display this help message and exit
 EOF
 }
 
 main() {
-  CURL=$(which curl)
+  CURL=$(command -v curl)
+
   VERSION=$("${CURL}" --silent "https://api.github.com/repos/${1}/releases/latest" |
   grep -Po "(?<=\"tag_name\": \").*(?=\")")
 
@@ -27,26 +29,35 @@ main() {
   unset VERSION
 }
 
-if [ "$#" -eq 0 ]; then
-  echo "$(basename "${0}"): missing argument"
-  echo "Try '$(basename "${0}") -h' for more information."
-  exit 1
-fi
+parse_params() {
+  while true; do
+    case "${1-}" in
+      "-h"|"--help")
+        usage
+        exit 0
+        ;;
+      "-V"|"--verbose")
+        set -x
+        ;;
+      -?*)
+        echo "$(basename "${0}"): Invalid option ${1}"
+        echo "Try '$(basename "${0}") -h' for more information."
+        exit 1
+        ;;
+      *)
+        break
+        ;;
+    esac
+    shift
+  done
 
-while true; do
-  case "${1-}" in
-    "-h"|"--help")
-      usage
-      exit 0
-      ;;
-    -?*)
-      echo "$(basename "${0}"): Invalid option ${1}"
-      echo "Try '$(basename "${0}") -h' for more information."
-      exit 1
-      ;;
-    *)
-      main "${1}"
-      break
-      ;;
-  esac
-done
+  if [ -z "$1" ]; then
+    echo "$(basename "${0}"): USERNAME/REPO is required."
+    echo "Try '$(basename "${0}") -h' for more information."
+    exit 1
+  fi
+
+  main "$@"
+}
+
+parse_params "$@"
diff --git a/bin/git-ssh-origin b/bin/git-ssh-origin
--- a/bin/git-ssh-origin
+++ b/bin/git-ssh-origin
@@ -5,14 +5,16 @@
 
 usage() {
   cat <<EOF
-Usage: $(basename "${0}") [option]
+Usage: $(basename "${0}") [options]
 
-  -h, --help  display this help message and exit
+  -V, --verbose    output debug information
+  -h, --help       display this help message and exit
 EOF
 }
 
 main() {
-  ORIGINAL_URL=$(git remote get-url origin)
+  GIT=$(command -v git)
+  ORIGINAL_URL=$(${GIT} remote get-url origin)
 
   if [ "${ORIGINAL_URL#git@}" != "$ORIGINAL_URL" ]; then
     echo "Already an SSH URL: $ORIGINAL_URL"
@@ -21,7 +23,7 @@ main() {
 
   UPDATED_URL=$(echo "$ORIGINAL_URL" | sed 's/https:\/\//git@/' | sed 's/\//:/')
 
-  git remote set-url origin "$UPDATED_URL"
+  ${GIT} remote set-url origin "$UPDATED_URL"
 
   if [ $? -eq 0 ]; then
     echo "Origin URL was updated"
@@ -31,22 +33,35 @@ main() {
     echo "Failed to update Git origin URL."
     exit 1
   fi
+
+  unset GIT
+  unset ORIGINAL_URL
+  unset UPDATED_URL
 }
 
-while true; do
-  case "${1-}" in
-    "-h"|"--help")
-      usage
-      exit 0
-      ;;
-    -?*)
-      echo "$(basename "${0}"): Invalid option ${1}"
-      echo "Try '$(basename "${0}") -h' for more information."
-      exit 1
-      ;;
-    *)
-      main
-      break
-      ;;
-  esac
-done
+parse_params() {
+  while true; do
+    case "${1-}" in
+      "-h"|"--help")
+        usage
+        exit 0
+        ;;
+      "-V"|"--verbose")
+        set -x
+        ;;
+      -?*)
+        echo "$(basename "${0}"): Invalid option ${1}"
+        echo "Try '$(basename "${0}") -h' for more information."
+        exit 1
+        ;;
+      *)
+        break
+        ;;
+    esac
+    shift
+  done
+
+  main "$@"
+}
+
+parse_params "$@"
diff --git a/bin/httpc b/bin/httpc
--- a/bin/httpc
+++ b/bin/httpc
@@ -5,9 +5,10 @@
 
 usage() {
   cat <<EOF
-Usage: $(basename "${0}") [option] <code>
+Usage: $(basename "${0}") [options] HTTP_STATUS_CODE
 
-  -h, --help  display this help message and exit
+  -V, --verbose    output debug information
+  -h, --help       display this help message and exit
 EOF
 }
 
@@ -133,7 +134,7 @@ wiki_link() {
   echo "https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#${1}"
 }
 
-code() {
+main() {
   HTTP_TEXT=$(status_text "${1}")
 
   if [ "${HTTP_TEXT}" = "Unknown HTTP Code" ]; then
@@ -144,34 +145,37 @@ code() {
   WIKIPEDIA_LINK=$(wiki_link "${1}")
 
   echo "${1} ${HTTP_TEXT} - ${WIKIPEDIA_LINK}"
-
-  unset HTTP_TEXT
-  unset WIKIPEDIA_LINK
 }
 
-if [ "$#" -eq 0 ]; then
-  echo "$(basename "${0}"): missing argument"
-  echo "Try '$(basename "${0}") -h' for more information."
-  exit 1
-fi
+parse_params() {
+  while true; do
+    case "${1-}" in
+      "-h"|"--help")
+        usage
+        exit 0
+        ;;
+      "-V"|"--verbose")
+        set -x
+        ;;
+      -?*)
+        echo "$(basename "${0}"): Invalid option ${1}"
+        echo "Try '$(basename "${0}") -h' for more information."
+        exit 1
+        ;;
+      *)
+        break
+        ;;
+    esac
+    shift
+  done
 
-while true; do
-  case "${1-}" in
-    "-h"|"--help")
-      usage
-      exit 0
-      ;;
-    -?*)
-      echo "$(basename "${0}"): Invalid option $1"
-      echo "Try '$(basename "${0}") -h' for more information."
-      exit 1
-      ;;
-    *)
-      code "$@"
-      break
-      ;;
-  esac
-  shift
-done
+  if [ -z "$1" ]; then
+    echo "$(basename "${0}"): HTTP_STATUS_CODE is required."
+    echo "Try '$(basename "${0}") -h' for more information."
+    exit 1
+  fi
 
+  main "$@"
+}
 
+parse_params "$@"
diff --git a/bin/nfo b/bin/nfo
--- a/bin/nfo
+++ b/bin/nfo
@@ -5,14 +5,15 @@
 
 usage() {
   cat <<EOF
-Usage: $(basename "${0}") [option] <file>
+Usage: $(basename "${0}") [options] FILE
 
-  -h, --help  display this help message and exit
+  -V, --verbose    output debug information
+  -h, --help       display this help message and exit
 EOF
 }
 
 nfo() {
-  ICONV=$(which iconv)
+  ICONV=$(command -v iconv)
 
   if [ -f "${1}" ]; then
     if [ "$(echo "${1}" | rev | cut -d. -f1 | rev)" = "nfo" ]; then
@@ -29,26 +30,35 @@ nfo() {
   unset ICONV
 }
 
-if [ "$#" -eq 0 ]; then
-  echo "$(basename "${0}"): missing argument"
-  echo "Try '$(basename "${0}") -h' for more information."
-  exit 1
-fi
+parse_params() {
+  while true; do
+    case "${1-}" in
+      "-h"|"--help")
+        usage
+        exit 0
+        ;;
+      "-V"|"--verbose")
+        set -x
+        ;;
+      -?*)
+        echo "$(basename "${0}"): Invalid option ${1}"
+        echo "Try '$(basename "${0}") -h' for more information."
+        exit 1
+        ;;
+      *)
+        break
+        ;;
+    esac
+    shift
+  done
 
-while true; do
-  case "${1}" in
-    "-h"|"--help")
-      usage
-      exit 0
-      ;;
-    -?*)
-      echo "$(basename "${0}"): Invalid option ${1}"
-      echo "Try '$(basename "${0}") -h' for more information."
-      exit 1
-      ;;
-    *)
-      nfo "${1}"
-      break
-      ;;
-  esac
-done
+  if [ -z "$1" ]; then
+    echo "$(basename "${0}"): FILE is required."
+    echo "Try '$(basename "${0}") -h' for more information."
+    exit 1
+  fi
+
+  nfo "$@"
+}
+
+parse_params "$@"
diff --git a/bin/vault b/bin/vault
--- a/bin/vault
+++ b/bin/vault
@@ -6,14 +6,15 @@
 
 usage() {
   cat <<EOF
-Usage: $(basename "${0}") [option] <file>
+Usage: $(basename "${0}") [options] FILE
 
-  -h, --help  display this help message and exit
+  -V, --verbose    output debug information
+  -h, --help       display this help message and exit
 EOF
 }
 
 vault() {
-  CURL=$(which curl)
+  CURL=$(command -v curl)
   VAULT_URL="https://vault.tf"
   VAULT_SECRET_KEY="${VAULT_SECRET_KEY}"
 
@@ -33,27 +34,35 @@ vault() {
   unset VAULT_SECRET_KEY
 }
 
-if [ "$#" -eq 0 ]; then
-  echo "$(basename "${0}"): missing argument"
-  echo "Try '$(basename "${0}") -h' for more information."
-  exit 1
-fi
+parse_params() {
+  while true; do
+    case "${1-}" in
+      "-h"|"--help")
+        usage
+        exit 0
+        ;;
+      "-V"|"--verbose")
+        set -x
+        ;;
+      -?*)
+        echo "$(basename "${0}"): Invalid option ${1}"
+        echo "Try '$(basename "${0}") -h' for more information."
+        exit 1
+        ;;
+      *)
+        break
+        ;;
+    esac
+    shift
+  done
 
-while true; do
-  case "${1-}" in
-    "-h"|"--help")
-      usage
-      exit 0
-      ;;
-    -?*)
-      echo "$(basename "${0}"): Invalid option ${1}"
-      echo "Try '$(basename "${0}") -h' for more information."
-      exit 1
-      ;;
-    *)
-      vault "$@"
-      break
-      ;;
-  esac
-  shift
-done
+  if [ -z "$1" ]; then
+    echo "$(basename "${0}"): FILE is required."
+    echo "Try '$(basename "${0}") -h' for more information."
+    exit 1
+  fi
+
+  vault "$@"
+}
+
+parse_params "$@"
diff --git a/bin/weather b/bin/weather
--- a/bin/weather
+++ b/bin/weather
@@ -6,16 +6,17 @@
 
 usage() {
   cat <<EOF
-Usage: $(basename "${0}") [option]
+Usage: $(basename "${0}") [options] LOCATION
 
-  -l, --location  return weather for location (default: Luxembourg,Luxembourg)
+  -l, --location LOCATION   return weather for location (default: Luxembourg,Luxembourg)
 
-  -h, --help      display this help message and exit
+  -V, --verbose             output debug information
+  -h, --help                display this help message and exit
 EOF
 }
 
 query() {
-  CURL=$(which curl)
+  CURL=$(command -v curl)
 
   if ! RESPONSE=$("${CURL}" --disable --fail --silent --compressed https://wttr.in/${LOCATION:-Luxembourg,Luxembourg}?2nqmF); then
     echo "$(basename "${0}"): An error occured, please try again"
@@ -28,25 +29,33 @@ query() {
   unset RESPONSE
 }
 
-while true; do
-  case "${1-}" in
-    "-h"|"--help")
-      usage
-      exit 0
-      ;;
-    "-l"|"--location")
-      LOCATION="${2-}"
-      shift
-      ;;
-    -?*)
-      echo "$(basename "${0}"): Invalid option ${1}"
-      echo "Try '$(basename "${0}") -h' for more information."
-      exit 1
-      ;;
-    *)
-      query "$@"
-      exit 0
-      ;;
-  esac
-  shift
-done
+parse_params() {
+  while true; do
+    case "${1-}" in
+      "-h"|"--help")
+        usage
+        exit 0
+        ;;
+      "-l"|"--location")
+        LOCATION="${2-}"
+        shift
+        ;;
+      "-V"|"--verbose")
+        set -x
+        ;;
+      -?*)
+        echo "$(basename "${0}"): Invalid option ${1}"
+        echo "Try '$(basename "${0}") -h' for more information."
+        exit 1
+        ;;
+      *)
+        break
+        ;;
+    esac
+    shift
+  done
+
+  query "$@"
+}
+
+parse_params "$@"
diff --git a/bin/whatsmyip b/bin/whatsmyip
--- a/bin/whatsmyip
+++ b/bin/whatsmyip
@@ -3,62 +3,79 @@
 # whatsmyip - return public IPv[4|6] address
 #
 
-# TODO:
-# - add -s/--strip option to allow for removal of newline `\n` from output
-
 usage() {
   cat <<EOF
-Usage: $(basename "${0}") [option]
+Usage: $(basename "${0}") [options]
 
-  -4, --IPv4   return public IPv4 if present
-  -6, --IPv6   return public IPv6 if present
-  -a, --all    return both IPv4 and IPv6 if present
+  -4, --IPv4       return public IPv4 if present
+  -6, --IPv6       return public IPv6 if present
+  -a, --all        return both IPv4 and IPv6 if present
+  -s, --strip      remove newline from output
 
-  -h, --help   display this help message and exit
+  -V, --verbose    output debug information
+  -h, --help       display this help message and exit
 EOF
 }
 
 query() {
-  CURL=$(which curl)
+  CURL=$(command -v curl)
 
-  if ! RESPONSE=$("${CURL}" --disable --fail --silent --compressed https://"${PROTO:-ipv4}".icanhazip.com/); then
-    echo "$(basename "${0}"): An error occured, please try again"
+  if ! RESPONSE=$("${CURL}" --disable --fail --silent --compressed https://"${1}".icanhazip.com/); then
+    echo "$(basename "${0}"): An error occurred, please try again"
     exit 1
   fi
 
-  echo "${RESPONSE}"
+  if [ "${STRIP}" = "true" ]; then
+    echo -n "${RESPONSE}"
+  else
+    echo "${RESPONSE}"
+  fi
 
   unset CURL
   unset RESPONSE
 }
 
-while true; do
-  case "${1-}" in
-    "-h"|"--help")
-      usage
-      exit 0
-      ;;
-    "-4"|"--IPv4")
-      PROTO="ipv4" query
-      exit 0
-      ;;
-    "-6"|"--IPv6")
-      PROTO="ipv6" query
-      exit 0
-      ;;
-    "-a"|"--all")
-      PROTO="ipv4" query
-      PROTO="ipv6" query
-      exit 0
-      ;;
-    -?*)
-      echo "$(basename "${0}"): Invalid option ${1}"
-      echo "Try '$(basename "${0}") -h' for more information."
-      exit 1
-      ;;
-    *)
-      query
-      exit 0
-      ;;
-  esac
-done
+parse_params() {
+  while true; do
+    case "${1-}" in
+      "-h"|"--help")
+        usage
+        exit 0
+        ;;
+      "-4"|"--IPv4")
+        PROTO="ipv4"
+        ;;
+      "-6"|"--IPv6")
+        PROTO="ipv6"
+        ;;
+      "-a"|"--all")
+        ALL="true"
+        ;;
+      "-s"|"--strip")
+        STRIP="true"
+        ;;
+      "-V"|"--verbose")
+        set -x
+        ;;
+      -?*)
+        echo "$(basename "${0}"): Invalid option ${1}"
+        echo "Try '$(basename "${0}") -h' for more information."
+        exit 1
+        ;;
+      *)
+        break
+        ;;
+    esac
+    shift
+  done
+
+  if [ "${ALL}" = "true" ]; then
+    for PROTO in ipv4 ipv6; do
+      query "${PROTO}"
+    done
+  else
+    query "${PROTO:-ipv4}"
+  fi
+}
+
+parse_params "$@"
