add argument parsing, fix PATH expansion

diff --git a/bin/zinstall b/bin/zinstall
--- a/bin/zinstall
+++ b/bin/zinstall
@@ -3,10 +3,21 @@
 # zinstall - Painless Zig installation
 #
 # TODO
-# add -a/--arch ro specify ${ARCH}
-# add -v/--version to specify ${VERSION}
-# allow to download master ziglang
+# allow downloading "master" Ziglang (use https://zigbin.io/master/x86_64-linux.tar.xz ?)
 #
+
+usage() {
+  cat <<EOF
+Usage: $(basename "${0}") [option]
+
+  -a, --arch     Specify architecture.
+  -v, --version  Specify version.
+
+  -V, --verbose  Output debug information.
+
+  -h, --help     Display this help message and exit.
+EOF
+}
 
 VERSION=0.13.0
 ARCH=x86_64
@@ -34,12 +45,45 @@ install() {
 }
 
 conftest() {
-  grep -qxF "export PATH=$PATH:/usr/local/zig" "$HOME/.profile" || \
-  echo "export PATH=$PATH:/usr/local/zig" >> "$HOME/.profile" && \
+  grep -qxF 'export PATH=$PATH:/usr/local/zig' "$HOME/.profile" || \
+  echo 'export PATH=$PATH:/usr/local/zig' >> "$HOME/.profile" && \
   export PATH=$PATH:/usr/local/zig
 
   zig help
   zig version
+}
+
+parse_params() {
+  while true; do
+    case "${1-}" in
+      "-h"|"--help")
+        usage
+        exit 0
+        ;;
+      "-a"|"--architecture")
+        ARCH="${2-x86_64}"
+        shift
+        ;;
+      "-v"|"--version")
+        VERSION="${2-0.13.0}"
+        shift
+        ;;
+      "-V"|"--verbose")
+        set -x
+        ;;
+      -?*)
+        echo "$(basename "${0}"): Invalid option ${1}"
+        echo "Try '$(basename "${0}") -h' for more information."
+        exit 1
+        ;;
+      *)
+        break
+        ;;
+    esac
+    shift
+  done
+
+  return 0
 }
 
 main() {
@@ -48,4 +92,5 @@ main() {
   conftest
 }
 
+parse_params "$@"
 main
